# Generated by cpp11: do not edit by hand

dev_string_widths_c <- function(string, family, face, size, cex, unit) {
  .Call("_systemfonts_dev_string_widths_c", string, family, face, size, cex, unit)
}

dev_string_metrics_c <- function(string, family, face, size, cex, unit) {
  .Call("_systemfonts_dev_string_metrics_c", string, family, face, size, cex, unit)
}

load_emoji_codes_c <- function(all, default_text, base_mod) {
  invisible(.Call("_systemfonts_load_emoji_codes_c", all, default_text, base_mod))
}

emoji_split_c <- function(string, path, index) {
  .Call("_systemfonts_emoji_split_c", string, path, index)
}

match_font_c <- function(family, italic, bold) {
  .Call("_systemfonts_match_font_c", family, italic, bold)
}

system_fonts_c <- function() {
  .Call("_systemfonts_system_fonts_c")
}

reset_font_cache_c <- function() {
  invisible(.Call("_systemfonts_reset_font_cache_c"))
}

get_font_info_c <- function(path, index, size, res) {
  .Call("_systemfonts_get_font_info_c", path, index, size, res)
}

get_glyph_info_c <- function(glyphs, path, index, size, res) {
  .Call("_systemfonts_get_glyph_info_c", glyphs, path, index, size, res)
}

register_font_c <- function(family, paths, indices, features, settings) {
  invisible(.Call("_systemfonts_register_font_c", family, paths, indices, features, settings))
}

clear_registry_c <- function() {
  invisible(.Call("_systemfonts_clear_registry_c"))
}

registry_fonts_c <- function() {
  .Call("_systemfonts_registry_fonts_c")
}

get_string_shape_c <- function(string, id, path, index, size, res, lineheight, align, hjust, vjust, width, tracking, indent, hanging, space_before, space_after) {
  .Call("_systemfonts_get_string_shape_c", string, id, path, index, size, res, lineheight, align, hjust, vjust, width, tracking, indent, hanging, space_before, space_after)
}

get_line_width_c <- function(string, path, index, size, res, include_bearing) {
  .Call("_systemfonts_get_line_width_c", string, path, index, size, res, include_bearing)
}
